.PHONY: simple average complex all

simple:
	node run-tests.js --category simple

average:
	node run-tests.js --category average

complex:
	node run-tests.js --category complex

all:
	node run-tests.js --all
