.PHONY: simple average complex all simple-bl average-bl complex-bl all-bl

simple:
	node run-tests.js --category simple

average:
	node run-tests.js --category average

complex:
	node run-tests.js --category complex

all:
	node run-tests.js --all

simple-bl:
	node run-tests.js --category simple --with-blender

average-bl:
	node run-tests.js --category average --with-blender

complex-bl:
	node run-tests.js --category complex --with-blender

all-bl:
	node run-tests.js --all --with-blender
