"""Shared tactile map geometry/rendering constants."""

# Feature heights and base geometry.
ROAD_HEIGHT_CAR_MM = 0.82  # 3 x 0.25-0.3mm layers
ROAD_HEIGHT_PEDESTRIAN_MM = 1.5
BUILDING_HEIGHT_MM = 2.9
BASE_HEIGHT_MM = 0.6
BASE_OVERLAP_MM = 0.01

# Water geometry.
WATER_AREA_DEPTH_MM = 1.5
WATER_WAVE_DISTANCE_MM = 10.3
WATERWAY_DEPTH_MM = 0.55  # 2 x 0.25-0.3mm layers

# Border geometry.
BORDER_WIDTH_MM = 1.2
BORDER_HORIZONTAL_OVERLAP_MM = 0.05
BORDER_HEIGHT_MM = (ROAD_HEIGHT_PEDESTRIAN_MM + BUILDING_HEIGHT_MM) / 2

# Marker geometry.
MARKER_HEIGHT_MM = BUILDING_HEIGHT_MM + 2
MARKER_RADIUS_MM = MARKER_HEIGHT_MM * 0.5

# Wireframe render defaults.
WIREFRAME_RENDER_RESOLUTION = 1024
WIREFRAME_CAMERA_PADDING = 1.02
WIREFRAME_CAMERA_MIN_SCALE = 1.0
